version: '2.4'
services:
  bot:
    build: ./app
    container_name: bot
    restart: always
    env_file:
      - .env
    depends_on:
      - bot_db

  bot_db:
      image: postgres:13.0
      restart: always
      container_name: bot_db
      volumes:
        - postgres_data:/var/lib/postgresql/data/
        - ./migrations:/docker-entrypoint-initdb.d
      env_file:
        - .env
      ports:
        - 5432:5432

volumes:
  postgres_data: